# Generated by Django 5.2.8 on 2026-09-20 03:40

import core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_seed_new_lists"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=160)),
                ("job_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "monthly_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="What a normal month's salary is. Pre-fills the salary payment.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("hired_on", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Off for somebody who has left. Their pay history stays.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"group": "EMPLOYEE_JOB"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.option",
                    ),
                ),
                (
                    "note_tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="A coloured mark on the notes, so their meaning shows first.",
                        limit_choices_to={"group": "NOTE_TAG"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.option",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=40, unique=True
                    ),
                ),
                (
                    "spent_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "category_name",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK", "Bank transfer"),
                            ("MOBILE", "Mobile money"),
                            ("CHEQUE", "Cheque"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("payment_channel_name", models.CharField(blank=True, max_length=120)),
                ("payment_reference", models.CharField(blank=True, max_length=80)),
                (
                    "payee",
                    models.CharField(
                        blank=True,
                        help_text="Who was paid - the landlord, the garage, the fuel station.",
                        max_length=160,
                    ),
                ),
                ("pay_type_name", models.CharField(blank=True, max_length=120)),
                (
                    "pay_period",
                    models.DateField(
                        blank=True,
                        help_text="The month a salary is for - its first day.",
                        null=True,
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        upload_to=core.utils.receipt_upload_path,
                        validators=[core.utils.validate_receipt_file],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"group": "EXPENSE_CATEGORY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.option",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="expenses.employee",
                    ),
                ),
                (
                    "note_tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="A coloured mark on the notes, so their meaning shows first.",
                        limit_choices_to={"group": "NOTE_TAG"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.option",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member this record belongs to. Managers only ever see their own records; administrators see everyone's.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pay_type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"group": "EMPLOYEE_PAY_TYPE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.option",
                    ),
                ),
                (
                    "payment_channel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which bank or wallet it was paid from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.option",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_voided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-spent_on", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(("monthly_salary__gte", 0)),
                name="employee_salary_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["owner", "-spent_on"], name="exp_owner_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["employee", "-spent_on"], name="exp_employee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
            ),
        ),
    ]
