# Generated by Django 5.2.8 on 2026-09-26 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("production", "0005_batch_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="group_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The reference of the first line of a payment with several lines.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="production_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="production.productionrun",
            ),
        ),
    ]
