# Generated by Django 5.2.8 on 2026-09-10 07:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_alter_stockmovement_movement_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=40, unique=True
                    ),
                ),
                (
                    "quantity_produced",
                    models.PositiveIntegerField(
                        help_text="Good units that went into finished stock."
                    ),
                ),
                (
                    "quantity_rejected",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Units that failed. Materials were still consumed for them.",
                    ),
                ),
                ("produced_on", models.DateField(db_index=True)),
                (
                    "material_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of the materials consumed, at the cost of the day.",
                        max_digits=14,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="material_cost divided by the good units produced.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("REVERSED", "Reversed")],
                        db_index=True,
                        default="COMPLETED",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                ("reversal_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member this record belongs to. Managers only ever see their own records; administrators see everyone's.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_runs",
                        to="inventory.product",
                    ),
                ),
                (
                    "reversed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_reversals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Production run",
                "ordering": ["-produced_on", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short code for the store card. Auto-generated if left blank.",
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("KG", "Kilogram"),
                            ("TONNE", "Tonne"),
                            ("BAG", "Bag"),
                            ("M3", "Cubic metre"),
                            ("LITRE", "Litre"),
                            ("PIECE", "Piece"),
                            ("METER", "Metre"),
                            ("ROLL", "Roll"),
                        ],
                        default="KG",
                        max_length=10,
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Cached running total. Derived from MaterialMovement history.",
                        max_digits=14,
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Warn at or below this quantity.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="What one unit costs to buy. Drives the cost of a batch.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "allow_negative_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Permit consuming below zero. Off by default.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff member this record belongs to. Managers only ever see their own records; administrators see everyone's.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_materials",
                        to="inventory.supplier",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Raw material",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="production.productionrun",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_lines",
                        to="production.rawmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["material__name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Delivery received"),
                            ("CONSUMED", "Used in production"),
                            ("WASTE", "Spoiled / written off"),
                            ("RETURN_OUT", "Returned to supplier"),
                            ("ADJUSTMENT", "Stock count correction"),
                            ("PRODUCTION_REVERSAL", "Returned by a reversed run"),
                            ("OPENING", "Opening balance"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Signed change. Positive = received, negative = used.",
                        max_digits=14,
                    ),
                ),
                (
                    "quantity_before",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "quantity_after",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per unit at the time of the movement.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Linked document: a production run, or a supplier invoice.",
                        max_length=60,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="production.rawmaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material movement",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "output_quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many finished units the quantities below produce.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe",
                        to="inventory.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "ordering": ["product__name"],
            },
        ),
        migrations.CreateModel(
            name="RecipeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="How much of this material one batch uses.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_items",
                        to="production.rawmaterial",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["material__name"],
            },
        ),
        migrations.AddIndex(
            model_name="productionrun",
            index=models.Index(
                fields=["product", "-produced_on"],
                name="production__product_163bd5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionrun",
            index=models.Index(
                fields=["owner", "-produced_on"], name="production__owner_i_0b63a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionrun",
            index=models.Index(
                fields=["status", "-produced_on"], name="production__status_ed4487_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawmaterial",
            index=models.Index(
                fields=["is_active", "is_deleted"],
                name="production__is_acti_631cf4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawmaterial",
            index=models.Index(
                fields=["owner", "is_active", "is_deleted"],
                name="material_owner_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawmaterial",
            index=models.Index(fields=["name"], name="production__name_d2928e_idx"),
        ),
        migrations.AddConstraint(
            model_name="rawmaterial",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_cost__gte", 0)),
                name="material_unit_cost_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawmaterial",
            constraint=models.UniqueConstraint(
                fields=("owner", "code"), name="material_code_unique_per_owner"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionmaterial",
            constraint=models.UniqueConstraint(
                fields=("run", "material"), name="production_material_once"
            ),
        ),
        migrations.AddIndex(
            model_name="materialmovement",
            index=models.Index(
                fields=["material", "-created_at"],
                name="production__materia_10eb46_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialmovement",
            index=models.Index(
                fields=["movement_type", "-created_at"],
                name="production__movemen_be95ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialmovement",
            index=models.Index(
                fields=["reference"], name="production__referen_af9520_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.UniqueConstraint(
                fields=("recipe", "material"), name="recipe_material_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="recipe_item_quantity_positive",
            ),
        ),
    ]
