# Generated by Django 5.2.8 on 2026-09-26 05:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_note_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionrun",
            name="other_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="What else was paid to make this batch - recorded as expenses.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="productionrun",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Materials plus other costs, divided by the good units produced.",
                max_digits=12,
            ),
        ),
    ]
