# Generated by Django 5.2.8 on 2026-10-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_batch_costs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialmovement",
            name="corrected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="materialmovement",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="materialmovement",
            name="corrected_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="What was really delivered; 0 when the delivery never happened.",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="materialmovement",
            name="corrected_unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="materialmovement",
            name="correction_note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
