# Generated by Django 5.2.8 on 2026-08-22 05:41

import core.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum debt allowed. 0 means no limit enforced.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_terms_days', models.PositiveIntegerField(default=30, help_text='Default number of days until a new debt falls due.')),
                ('total_credit_extended', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('outstanding_balance', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('last_purchase_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False, help_text='Block further credit sales to this customer.')),
                ('block_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='sales.customer')),
            ],
            options={
                'verbose_name': 'Credit account',
                'ordering': ['-outstanding_balance'],
            },
        ),
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Amount borrowed - the unpaid portion of the sale.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially repaid'), ('SETTLED', 'Settled'), ('WRITTEN_OFF', 'Written off'), ('CANCELLED', 'Cancelled (sale voided)')], db_index=True, default='OPEN', max_length=12)),
                ('issued_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(db_index=True)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('write_off_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='sales.customer')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debt_record', to='sales.transaction')),
                ('written_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts_written_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank transfer'), ('MOBILE', 'Mobile money'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('GOODS_RETURN', 'Goods returned'), ('WRITE_OFF', 'Written off')], default='CASH', max_length=14)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('external_reference', models.CharField(blank=True, help_text='Bank slip number, mobile-money transaction ID, cheque number.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('is_reversed', models.BooleanField(db_index=True, default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='credit.debtrecord')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repayments_received', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.utils.receipt_upload_path, validators=[core.utils.validate_receipt_file])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='credit.repayment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repayment proof',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['customer', 'status'], name='credit_debt_custome_9d7323_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['status', 'due_date'], name='credit_debt_status_357119_idx'),
        ),
        migrations.AddIndex(
            model_name='debtrecord',
            index=models.Index(fields=['-created_at'], name='credit_debt_created_9ecc3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gte', 0)), name='debt_principal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='debtrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount_repaid__gte', 0)), name='debt_repaid_non_negative'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['debt', '-paid_at'], name='credit_repa_debt_id_ee4894_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['-paid_at'], name='credit_repa_paid_at_9ba4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='repayment',
            index=models.Index(fields=['is_reversed'], name='credit_repa_is_reve_ca4435_idx'),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='repayment_amount_positive'),
        ),
    ]
