# Generated by Django 5.2.8 on 2026-09-20 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_seed_new_lists"),
        ("credit", "0003_alter_debtrecord_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditaccount",
            name="note_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A coloured mark on the notes, so their meaning shows first.",
                limit_choices_to={"group": "NOTE_TAG"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.option",
            ),
        ),
        migrations.AddField(
            model_name="debtrecord",
            name="note_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A coloured mark on the notes, so their meaning shows first.",
                limit_choices_to={"group": "NOTE_TAG"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.option",
            ),
        ),
        migrations.AddField(
            model_name="repayment",
            name="note_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A coloured mark on the notes, so their meaning shows first.",
                limit_choices_to={"group": "NOTE_TAG"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.option",
            ),
        ),
    ]
