# Generated by Django 5.2.8 on 2026-08-22 05:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(db_index=True, help_text='Internal stock keeping unit. Auto-generated if left blank.', max_length=60, unique=True)),
                ('barcode', models.CharField(blank=True, db_index=True, help_text='EAN/UPC scanned at the counter. Leave blank if none.', max_length=60, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('PIECE', 'Piece'), ('BOX', 'Box'), ('CARTON', 'Carton'), ('KG', 'Kilogram'), ('LITRE', 'Litre'), ('METER', 'Meter'), ('PACK', 'Pack')], default='PIECE', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What you pay. Visible to Administrators only.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='What the customer pays.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Cached running total. Derived from StockMovement history.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Raise a low-stock alert at or below this quantity.')),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Permit selling below zero (back-orders). Off by default.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock / Purchase in'), ('SALE', 'Sale'), ('RETURN_IN', 'Customer return (in)'), ('RETURN_OUT', 'Return to supplier (out)'), ('ADJUSTMENT', 'Manual adjustment'), ('DAMAGE', 'Damage / write-off'), ('VOID_REVERSAL', 'Reversal of voided sale'), ('OPENING', 'Opening balance')], db_index=True, max_length=15)),
                ('quantity_delta', models.IntegerField(help_text='Signed change. Positive = stock in, negative = stock out.')),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost at the time of the movement (restocks).', max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price at the time of the movement (sales).', max_digits=12, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, help_text='Linked document, e.g. TXN-20260821-0007 or a supplier invoice no.', max_length=60)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock movement',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='inventory_s_product_cfb4fb_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'), models.Index(fields=['reference'], name='inventory_s_referen_16defd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_deleted'], name='inventory_p_is_acti_d704d0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='inventory_p_categor_471092_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='product_cost_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='product_selling_price_non_negative'),
        ),
    ]
