# Generated by Django 5.2.8 on 2026-09-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_product_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("RESTOCK", "Restock / Purchase in"),
                    ("SALE", "Sale"),
                    ("RETURN_IN", "Customer return (in)"),
                    ("RETURN_OUT", "Return to supplier (out)"),
                    ("ADJUSTMENT", "Manual adjustment"),
                    ("DAMAGE", "Damage / write-off"),
                    ("VOID_REVERSAL", "Reversal of voided sale"),
                    ("OPENING", "Opening balance"),
                    ("PRODUCTION", "Produced in-house"),
                    ("PRODUCTION_REVERSAL", "Reversal of a production run"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
