# Generated by Django 5.2.8 on 2026-10-03 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_audit_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="corrected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="corrected_quantity",
            field=models.IntegerField(
                blank=True,
                help_text="What was really received; 0 when the restock never happened.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="corrected_unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="correction_note",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
