# Generated by Django 5.2.8 on 2026-09-20 03:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_seed_new_lists"),
        ("inventory", "0006_note_tag"),
        ("sales", "0005_note_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=40, unique=True
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "received_by_name",
                    models.CharField(
                        blank=True,
                        help_text="Who took the goods - the customer, or their driver.",
                        max_length=160,
                    ),
                ),
                ("received_by_phone", models.CharField(blank=True, max_length=30)),
                (
                    "vehicle",
                    models.CharField(
                        blank=True,
                        help_text="Plate number, if it left on a lorry.",
                        max_length=40,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_voided", models.BooleanField(db_index=True, default=False)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Deliveries",
                "ordering": ["-delivered_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Waiting for collection"),
                    ("PARTIAL", "Part collected"),
                    ("DELIVERED", "Fully collected"),
                ],
                db_index=True,
                default="PENDING",
                editable=False,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="transactionitem",
            name="quantity_delivered",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name="transactionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_delivered__lte", models.F("quantity"))),
                name="item_delivered_within_sold",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="delivered_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="note_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="A coloured mark on the notes, so their meaning shows first.",
                limit_choices_to={"group": "NOTE_TAG"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.option",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="sales.transaction",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_voided",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliveryline",
            name="delivery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="sales.delivery",
            ),
        ),
        migrations.AddField(
            model_name="deliveryline",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_lines",
                to="sales.transactionitem",
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["transaction", "-delivered_at"], name="dlv_txn_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="delivery_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryline",
            constraint=models.UniqueConstraint(
                fields=("delivery", "item"), name="delivery_line_once_per_item"
            ),
        ),
    ]
