# Generated by Django 5.2.8 on 2026-10-09 16:19

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_existing_sales_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="id_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The number on that card. Searchable from the list.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="id_photo",
            field=models.ImageField(
                blank=True,
                help_text="A photograph of their identity card, licence or passport.",
                null=True,
                upload_to=core.utils.id_photo_upload_path,
                validators=[core.utils.validate_person_photo],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="A photograph of the person. Square pictures look best.",
                null=True,
                upload_to=core.utils.person_photo_upload_path,
                validators=[core.utils.validate_person_photo],
            ),
        ),
    ]
